name: curve-tricrypto-ng
contracts_folder: contracts/main/

plugins:
  - name: vyper
  - name: alchemy
  - name: hardhat
  - name: ledger
  - name: etherscan
  - name: arbitrum
  - name: optimism
  - name: polygon

default_ecosystem: ethereum

hardhat:
  port: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
      sepolia:
        upstream_provider: alchemy

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    transaction_acceptance_timeout: 99999999
    default_provider: hardhat
  mainnet:
    transaction_acceptance_timeout: 99999999
  sepolia:
    transaction_acceptance_timeout: 99999999

geth:
  ethereum:
    mainnet:
      uri: http://localhost:9090

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 5
